---
- name: rebuild login database
  command: find /etc/login.conf.d/ -type f -exec cap_mkdb /etc/login.conf {} +

- name: set hostname
  command: hostname "{{ hostname }}"

- name: update man database
  command: makewhatis
